# Generated by Django 3.2.9 on 2024-05-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankUsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('gend', models.CharField(max_length=8)),
                ('birdate', models.IntegerField(default=0)),
                ('birmonth', models.CharField(max_length=10)),
                ('biryear', models.IntegerField(default=0)),
                ('custaddress', models.TextField()),
                ('custpincode', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=10)),
                ('custmail', models.EmailField(max_length=254, unique=True)),
                ('aadhaar', models.CharField(max_length=12)),
                ('pan', models.CharField(max_length=10)),
                ('custpassword', models.CharField(max_length=20)),
            ],
        ),
    ]
